{{- $redisHosts := printf "%v:%v:%v" .Values.redis.host .Values.redis.port "us-east-1c" -}}
{{- if .Values.redis.password -}}
  {{- $redisHosts = printf "%v:%v" $redisHosts .Values.redis.password -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: orkesregistry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: orkesdeploymentsecrets
type: Opaque
data:
  redisHosts: {{ $redisHosts | b64enc }}
  redisPassword: {{ .Values.redis.password | b64enc }}
  postgresPassword: {{ .Values.postgres.password | b64enc }}
  securityJwtSecret: {{ .Values.security.jwt.secret | b64enc }}
  auth0ClientSecret: {{ .Values.security.auth0.clientSecret | b64enc }}