apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orkes-conductor-standalone.fullname" . }}
  labels:
    {{- include "orkes-conductor-standalone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orkes-conductor-standalone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orkes-conductor-standalone.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: liveness-port
              containerPort: {{ .Values.image.livenessPort }}
          startupProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: orkesregistry