app:
  replicaCount: 1
  jvmSettings: "-Xms256M -Xmx384M"
  resources:
    cpuLimit: "0.5"
    memoryLimit: "512M"
    cpuRequests: "0.5"
    memoryRequests: "512M"

workers:
  replicaCount: 1
  jvmSettings: "-Xms256M -Xmx384M"
  resources:
    cpuLimit: "0.5"
    memoryLimit: "512M"
    cpuRequests: "0.5"
    memoryRequests: "512M"

redis:
  host: redis

postgres:
  username: postgres
  password: postgres
  url: jdbc:postgresql://postgres:5432/conductordb

imageCredentials:
  password: ""

security:
  enabled: false
